# Este es una prueba para manejo de git/github

Este es un mensaje generado en el mismo repositorio remoto

```
	let num = 0
	num = 10
	for i in range(num):
		print(num+i)
#conflicto solucionado
```
